name: Build and Test .NET API

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v4

    - name: Configurar .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restaurar dependencias
      run: dotnet restore ./Matricula.Api/Matricula.Api.csproj

    - name: Compilar proyecto
      run: dotnet build ./Matricula.Api/Matricula.Api.csproj --configuration Release --no-restore
